spring:
  application:
    name: novara
  datasource:
    username: ${NOVARA_SQL_USER:root}
    url: jdbc:mysql://localhost:3306/novara-main?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASS1:1q2w3e4r}
  jpa:
    show-sql: true
    open-in-view: 'false'
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'TRUE'
        validator:
          allow_multiple_cascaded_validation_on_composable_constraints: false
    hibernate:
      ddl-auto: update
app:
  jwt:
    issuer: "novara-space"
    secret: "${NOVARA_JWT_SECRET}"
    expiry-minutes: 15
    refresh-expiry-hours: 32

server:
  port: 8095